apiVersion: apps/v1
kind: Deployment
metadata:
  name: ex-cluster
spec:
  selector:
    matchLabels:
      app: ex-cluster
  replicas: 4
  template:
    metadata:
      labels:
        app: ex-cluster
    spec:
      serviceAccountName: serviceaccount-ex
      containers:
        - name: ex-cluster
          image: ex_cluster:local
          imagePullPolicy: Never
          resources:
            limits:
              memory: "128Mi"
              cpu: "200m"
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: NODE_COOKIE
              value: "cookie"
