apiVersion: v1
kind: ServiceAccount
metadata:
  name: serviceaccount-ex
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: role-ex
rules:
  - apiGroups:
      - ""
    resources:
      - endpoints
    verbs:
      - list
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rolebinding-ex
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: role-ex
subjects:
  - kind: ServiceAccount
    name: serviceaccount-ex

---
